### ISSUE TITLE
How can I read a Unsigned Int of 24 bits,three octets?

### ISSUE THREAD

**Issue by CristianMG** [DitchOoM/buffer#18]
I'm using this library to read bluetooth values, in some standards exist this type of value.
uint24. There are ways to read this, with this library.

**Comment by thebehera** [comment]
@CristianMG  in the latest version (1.1.3) you can try using [`ReadBuffer. writeNumberOfByteSize(3).toInt()`](https://github.com/DitchOoM/buffer/blob/05fe2ddae8a1bd25660d3d77de3bae9820aee45d/src/commonMain/kotlin/com/ditchoom/buffer/ReadBuffer.kt#L55)
