### ISSUE TITLE
Need absolute access functions

### ISSUE THREAD

**Issue by clydebarrow** [DitchOoM/buffer#34]
The ByteBuffer functions that allow fetching a data item from a specific position without moving the pointers are needed to make this a useful replacement for ByteBuffer, e.g. `ByteBuffer.get(index)` returns the byte at `index` without moving the `position`.

**Comment by thebehera** [comment]
Would https://github.com/DitchOoM/buffer/pull/35 work?

**Comment by clydebarrow** [comment]
On a quick look, it appears to have the necessary functionality.
