### ISSUE TITLE
How can I convert a ByteBuffer to a FloatBuffer (as java.nio.ByteBuffer#asFloatBuffer factory method)?

### ISSUE THREAD

**Issue by FavoRiteKK** [DitchOoM/buffer#36]
Hi, 
I want to reuse a Java implementation which converts a ByteBuffer to a FloatBuffer. How can I achieve this?
Thanks.

**Comment by thebehera** [comment]
There's currently no support for that! Pull requests are supported however :)

**Comment by FavoRiteKK** [comment]
Okay. Maybe I'll search for another approach!
