### ISSUE TITLE
Improving release process

### ISSUE THREAD

**Issue by jbruchanov** [DitchOoM/buffer#65]
Hi thanks a lot for your work. 

I'd have though few ideas for your release process...

- Use please github release tagging, so it's easier to see what changes you are doing in newer releases if you don't have proper release notes
- add explicit as low as possible jvmTarget, you've probably on your machine/CI updated JVM and now newer version (1.3.40+) is failing on my side with 
```
com/ditchoom/buffer/Charset has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```
- having versioning like 1.4.0 is not only for me sort sign of [semver](https://semver.org/), so I'd strongly suggest to strictly follow it, so 1.3.38 -> 1.3.40 won't break because you need newer version of JDK

thank you for considering these ^

**Comment by thebehera** [comment]
Hey I completely agree with you on this. I was attempting to update several components and it appears i might have unintentionally updated the java version. I will look in to correcting this.

For github release tagging, yes I am looking into automating this if possible however I have to research this. Thanks for the suggestion and I agree it's hard to track the releases with the current process

As for the semvar stuff, yes I agree and this shouldn't happen in the future. thanks!

**Comment by thebehera** [comment]
@jbruchanov Will https://github.com/DitchOoM/buffer/pull/66 fix your jvmTarget issues?

**Comment by jbruchanov** [comment]
> @jbruchanov Will #66 fix your jvmTarget issues?

awesome, yes it did help 👍
