### ISSUE TITLE
Failed resolution of: Lcom/ditchoom/buffer/BufferFactoryJvm;

### ISSUE THREAD

**Issue by ColtonIdle** [DitchOoM/buffer#69]
I'm writing a kmp library which uses this. It seems to work fine, but the second I add this library to another kmp project and try to run it on my android device I get this error. Not sure where I'm going wrong. Would appreciate any pointers as I feel like I'm maybe making a dumb mistake.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ditchoom/buffer/BufferFactoryJvm;
  at smart_buffer.SmartBuffer.<init>(SmartBuffer.kt:57)
```

My library has a build.gradle of

```
commonMain.dependencies {
            implementation("com.ditchoom:buffer:1.4.2")
```

Do I need to be explictly adding this library as a jvm dep or something?

**Comment by thebehera** [comment]
Can you provide a minimal sample project which reproduces this?

**Comment by ColtonIdle** [comment]
I was able to resolve if I updated my amp library to also support android. Closing!
